reusable composite action to process tests

diff --git a/.github/workflows/test-monitor-regular-skipped.yml b/.github/workflows/test-monitor-regular-skipped.yml
--- a/.github/workflows/test-monitor-regular-skipped.yml
+++ b/.github/workflows/test-monitor-regular-skipped.yml
@@ -75,36 +75,38 @@ jobs:
           # make VERBOSE=1 JSON_OUTPUT=true GO_TEST_PACKAGES=github.com/onflow/flow-go/admin/commands/common -es unittest-main > test-output
         # test run should continue even if there are failed tests
         continue-on-error: true
-      - name: Get commit date
-        id: commit_date
-        run: echo "::set-output name=date::$(git show --no-patch --no-notes --pretty='%cI' $COMMIT_SHA)"
-      - name: Get job run date
-        id: job_run_date
-        run: echo "::set-output name=date::$(TZ=":America/Los_Angeles" date -Iseconds)"
-      - name: Process test results
-        run: cat test-output | go run tools/test_monitor/level1/process_summary1_results.go
-        env:
-          JOB_STARTED: ${{ steps.job_run_date.outputs.date }}
-          COMMIT_DATE: ${{ steps.commit_date.outputs.date }}
-#      - name: Setup tmate session
-#        uses: mxschmitt/action-tmate@v3
-#        if: success() || failure()
-      - name: Set up Cloud SDK
-        uses: google-github-actions/setup-gcloud@v0
-        with:
-          service_account_key: ${{ secrets.GCP_SA_KEY }}
-      - name: Upload results to BigQuery (skipped tests)
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 1
-          max_attempts: 3
-          command: bq load --source_format=NEWLINE_DELIMITED_JSON $BIGQUERY_DATASET.$BIGQUERY_TABLE $SKIPPED_TESTS_FILE tools/test_monitor/schemas/skipped_tests_schema.json
-      - name: Upload results to BigQuery (test run)
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 2
-          max_attempts: 3
-          command: bq load --source_format=NEWLINE_DELIMITED_JSON $BIGQUERY_DATASET.$BIGQUERY_TABLE2 $RESULTS_FILE tools/test_monitor/schemas/test_results_schema.json
+      - name: Process test results (${{ matrix.targets.name }})
+        uses: ./.github/actions/test-monitor-process-tests
+#      - name: Get commit date
+#        id: commit_date
+#        run: echo "::set-output name=date::$(git show --no-patch --no-notes --pretty='%cI' $COMMIT_SHA)"
+#      - name: Get job run date
+#        id: job_run_date
+#        run: echo "::set-output name=date::$(TZ=":America/Los_Angeles" date -Iseconds)"
+#      - name: Process test results
+#        run: cat test-output | go run tools/test_monitor/level1/process_summary1_results.go
+#        env:
+#          JOB_STARTED: ${{ steps.job_run_date.outputs.date }}
+#          COMMIT_DATE: ${{ steps.commit_date.outputs.date }}
+##      - name: Setup tmate session
+##        uses: mxschmitt/action-tmate@v3
+##        if: success() || failure()
+#      - name: Set up Cloud SDK
+#        uses: google-github-actions/setup-gcloud@v0
+#        with:
+#          service_account_key: ${{ secrets.GCP_SA_KEY }}
+#      - name: Upload results to BigQuery (skipped tests)
+#        uses: nick-fields/retry@v2
+#        with:
+#          timeout_minutes: 1
+#          max_attempts: 3
+#          command: bq load --source_format=NEWLINE_DELIMITED_JSON $BIGQUERY_DATASET.$BIGQUERY_TABLE $SKIPPED_TESTS_FILE tools/test_monitor/schemas/skipped_tests_schema.json
+#      - name: Upload results to BigQuery (test run)
+#        uses: nick-fields/retry@v2
+#        with:
+#          timeout_minutes: 2
+#          max_attempts: 3
+#          command: bq load --source_format=NEWLINE_DELIMITED_JSON $BIGQUERY_DATASET.$BIGQUERY_TABLE2 $RESULTS_FILE tools/test_monitor/schemas/test_results_schema.json
 
 #  regular-skipped-test-run:
 #    name: Test Monitor - Regular, Skipped Tests Run
